name: Get Project IDs

on:
  workflow_dispatch:

permissions:
  contents: read
  projects: read

jobs:
  project-info:
    runs-on: ubuntu-latest

    steps:
      - name: Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Get Project Information
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api graphql -f query='
          {
            user(login:"JulianaBorges"){
              projectV2(number:7){
                id
                title

                fields(first:30){
                  nodes{

                    ... on ProjectV2FieldCommon{
                      id
                      name
                    }

                    ... on ProjectV2SingleSelectField{
                      id
                      name
                      options{
                        id
                        name
                      }
                    }

                    ... on ProjectV2IterationField{
                      id
                      name
                    }

                  }
                }
              }
            }
          }'